Biomass imports limited 142-472 PJ
KTH-dESA/OSeMBE_ECEMF pull request #48
Opened 2022-08-31 14:49 UTC by EmiFej

2022-08-31 21:01 UTC, HauHe requested changes
Hi @EmiFej , I now didn't review all files, but in the 2 scenarios I looked into you defined the `BMIM` correctly (from what I saw). But you also set the `TotalAnnualAcitivtiyUpperLimit` to 0, which is not needed and contradicts the emission limit.

2022-08-31 21:25 UTC, EmiFej commented on input_data/diagnostic_scen/diag-base/data/TotalTechnologyAnnualActivityUpperLimit.csv
> +REGION1,ATBM00I00,2015,0
Because we agreed that the landlocked countries would not be able to import biomass in this case? While the rest would be limited to the 142-472 PJ? AT is Austria and hence part of the landlocked ones. The `BMIM` is in place since it is needed for the limBio scenario (which is not the same as this issue #48.)

The `BMIM` is used in the limBio scenario and it is limiting technologies by the `AnnualEmissionLimit`, not the `TotalAnnualActivityUpperLimit`.

2022-08-31 21:27 UTC, EmiFej commented on input_data/diagnostic_scen/diag-c0to80-gr5/data/TotalTechnologyAnnualActivityUpperLimit.csv
> -REGION1,FRCOSTPH3,2015,99
@HauHe The same reasoning as above mentioned was applied to all scenarios but the LimBio. The LimBio instead has a ban on imports for all countries, hence the `TotalAnnualActivityUpperLimit` set to 0 for all BM00I00 technologies.

2022-09-01 07:25 UTC, HauHe commented on input_data/diagnostic_scen/diag-base/data/TotalTechnologyAnnualActivityUpperLimit.csv
> +REGION1,ATBM00I00,2015,0
Ah, alright, makes sense. Got late yesterday... Then I'll proceed

2022-09-01 07:27 UTC, HauHe commented on input_data/diagnostic_scen/diag-base/data/TotalTechnologyAnnualActivityUpperLimit.csv
> +REGION1,ATBM00I00,2015,0
Alright makes sense, didn't recall last night.

2022-09-01 07:36 UTC, merged