Changes to work with Otoole v1.0.3
KTH-dESA/OSeMBE_ECEMF pull request #61
Opened 2023-06-14 08:27 UTC by EmiFej

Changes include:

- Creation of a config.yaml file which is placed under the config folder. It includes the YearlyPeak and ReserveMarginTagTechnology for each country.

2023-06-16 06:48 UTC, willu47 requested changes
Hi @EmiFej. Good progress, but you need to find the source of the bug in `run.py` to close this off. See comments below.

2023-06-16 06:48 UTC, willu47 commented on run.py
> +#def get_duals(model):
Don't comment out the function definition here. It will create broken code and a potential source of bugs.

2023-06-16 06:48 UTC, willu47 commented on run.py
> +#def write_duals(dict_duals: dict, path: str):
Don't comment this out.

2023-06-16 06:48 UTC, willu47 commented on run.py
> +    #dual_path = snakemake.output[1]
No need to comment this.

2023-06-16 06:48 UTC, willu47 commented on run.py
> +    #write_duals(dic_duals, dual_path)
These two lines are the only parts you must comment to deactivate writing the dual writing.  I guess a bug in the dual-value extraction prevents the solution file from being generated.

2023-07-04 16:05 UTC, EmiFej commented on run.py
> +    #write_duals(dic_duals, dual_path)
Please see the latest commit @willu47 1d84c3d. Let me know if the changes are in line with what was requested form the comments in this review.

2023-07-05 07:37 UTC, willu47 requested changes
You still need to uncomment the function def lines on 20 and 26.

2023-07-05 07:37 UTC, willu47 commented on snakefile
> +        #"otoole convert csv datafile {input.dp_path} {output.df_path}"
Please remove this line 26

2023-07-05 07:37 UTC, willu47 commented on snakefile
> +         #directory("working_directory/{scen}_duals")
Add a comment explaining why this is commented out.

2023-07-05 07:37 UTC, willu47 commented on run.py
> +    #dual_path = snakemake.output[1]
Still to do

2023-07-05 07:37 UTC, willu47 commented on run.py
> +#def write_duals(dict_duals: dict, path: str):
Uncomment line 46

2023-07-05 07:37 UTC, willu47 commented on run.py
> +#def get_duals(model):
Uncomment line 20

2023-07-05 14:46 UTC, EmiFej commented
I'm not sure that everything is correct with my branch EmiFej-new-otoole-version. Some of the changes that you commented regarding the run.py file were already unhashed in my local version, but appeared as hashed out in the PR. Hopefully it is better now. Regarding the dual values I had issues with them before, hence the removal of all dual_value related parts of the code. I'm not sure if it was a code issue or on my end.

2023-07-07 13:23 UTC, EmiFej commented
In commit d431128 it stated that `src/` was not staged or committed. After staging, committing, and pushing it to origin and changing the branch from `new-otoole-version` to `main` I got the following message:

`warning: unable to rmdir 'src/openentrance': Directory not empty
Switched to branch 'main'
Your branch and 'origin/main' have diverged,
and have 1 and 7 different commits each, respectively.`

I'm not sure that the file should be there or have the name` src/openentrance`.

2023-07-10 09:38 UTC, merged