Changing versions of dependencies
KTH-dESA/OSeMBE_ECEMF pull request #64
Opened 2023-07-04 16:18 UTC by EmiFej

In this commit @willu47 and @EmiFej have changed the versions of some dependencies within the `openentrance-env`. This is to allow the `resultify.py` script to run by using the .append method, which is no longer supported by Pandas version `2` or newer. By using pandas less than `2` (such as `1.5`) one must use a Python version smaller than `3.11`. 

After running the `snakemake `workflow and specifying `--use-conda` in the shell command, the `openentrance-env` will install all dependencies. When this is completed, run:
`pip install -e  git+https://github.com/openENTRANCE/openentrance.git@main#egg=openentrance` 
in the terminal while in the `openentrance-env` environment.

2023-07-04 16:33 UTC, EmiFej commented
To this PR I also added the previous changes in solar potential, as well as the representation of solar potential in Latvia. Some rounding up of numbers which had many decimals have also been done.

2023-07-05 07:06 UTC, willu47 approved these changes

2023-07-05 07:38 UTC, willu47 commented on envs/openentrance_env.yaml
> +- pydantic < 2
Add comment `# required for nomenclature dependency of openentrance`

2023-07-05 07:40 UTC, willu47 requested changes
Almost ready to go.

Please add the installation instructions you've written in the PR into the readme.

2023-07-06 05:27 UTC, merged